### ISSUE TITLE
cannot identify the implementation class in Idea

### ISSUE THREAD

**Issue by metroRain** [domaframework/simple-boilerplate#38]
In your demo project I cloned locally, it shows EmployeeDaoImp cannot be resolved in my IDE but it runs successfully. on the other hand, in my project, which I imported Springboot framework, cannot initialize at beginning with my @autowired. im not sure if it is about my IDE version or not  that causes this issue

my IDE is Intellij Idea 2019.2

**Comment by nakamura-to** [comment]
Did you check the `Enable annotation processing` checkbox in your IDEA preferences?

See https://doma.readthedocs.io/en/stable/getting-started-idea/

Let me know if you have any questions.

**Comment by metroRain** [comment]
@nakamura-to 
Hi there
sorry for being late to response you

The problem is solved
I compared your demo on github(https://github.com/domaframework/simple-boilerplate.git) with my workspace and I found that I missed 
`annotationProcessor "org.seasar.doma:doma:${dependentVersion}"
    implementation "org.seasar.doma:doma:${dependentVersion}"`

Anyway, thank you for your reply
